import urllib.request
url = 'https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ8Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpbCiVodG1sXzE2ZTY0ZjQ4M2QyMjRjNjQ4MDY3MmNiMzJmNzgwNmEzEgsSBxCp9My8jRYYAZIBJAoKcHJvamVjdF9pZBIWQhQxMjAwMTA0OTEwMDU3ODg0NzA3Mw&filename=&opi=96797242'
urllib.request.urlretrieve(url, 'engineering-blog.html')
