import { Component, ChangeDetectionStrategy, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
import { HeaderComponent } from '../../../shared/components/header/header';

@Component({
  selector: 'app-article-details',
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  templateUrl: './article-details.html',
  styleUrl: './article-details.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ArticleDetailsComponent implements OnInit {
  articleId: string | null = null;

  article = {
    title: 'Optimizing Postgres for Write-Heavy Workloads',
    category: 'Databases',
    date: 'Jan 12, 2024',
    author: 'Dr. Elena Vance',
    authorRole: 'Principal Engineer',
    authorAvatar: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBf0EQJUd4P-jZghpQLsXzSlGGgpRB9uADcnA-LncH-7N1bkMLH_hu50MVH9ieBKzInz_5IA4Ojb5B4vXICKDFkJFpyiB-LQ3hY1KvdWAc-FWqKtFiDQ7sNaJgZQHbSCseKjaefHBrfUpeMx1dc0yNaoBQk5vcZz8p_qtCQsv5Qo4jQrnsu65p0KB0YOTLnuuT9XvkQ3dxvBH49Z7xb9X9V2mJWQFri2mzG26DafGTWFjPyreCrDwyXESrfZ_QwoVmlaLV6fuAWNhWP',
    coverImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBf0EQJUd4P-jZghpQLsXzSlGGgpRB9uADcnA-LncH-7N1bkMLH_hu50MVH9ieBKzInz_5IA4Ojb5B4vXICKDFkJFpyiB-LQ3hY1KvdWAc-FWqKtFiDQ7sNaJgZQHbSCseKjaefHBrfUpeMx1dc0yNaoBQk5vcZz8p_qtCQsv5Qo4jQrnsu65p0KB0YOTLnuuT9XvkQ3dxvBH49Z7xb9X9V2mJWQFri2mzG26DafGTWFjPyreCrDwyXESrfZ_QwoVmlaLV6fuAWNhWP',
    content: `
      <h2>The Challenge with Write-Heavy Workloads</h2>
      <p>When you are pushing thousands of transactions per second, PostgreSQL's default settings are rarely optimal. The Write-Ahead Log (WAL) can become a bottleneck, and VACUUM processes might struggle to keep up with the bloat generated by frequent UPDATEs and DELETEs.</p>
      
      <h3>1. Tuning the Write-Ahead Log (WAL)</h3>
      <p>The WAL is Postgres's mechanism for ensuring data integrity. Every transaction is written to the WAL before being flushed to the main data files. For write-heavy workloads, you want to minimize WAL I/O overhead.</p>
      <pre><code>max_wal_size = 16GB
min_wal_size = 4GB
checkpoint_timeout = 15min
checkpoint_completion_target = 0.9</code></pre>
      
      <h3>2. Taming Autovacuum</h3>
      <p>Dead tuples accumulate rapidly under heavy write pressure. If autovacuum doesn't run aggressively enough, your tables and indexes will bloat, destroying read performance and consuming massive amounts of disk space.</p>
      <pre><code>autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
autovacuum_vacuum_cost_limit = 2000
autovacuum_vacuum_cost_delay = 2ms</code></pre>

      <h3>3. Index Overhead Management</h3>
      <p>Every index on a table must be updated when a row is inserted or updated. This is often the hidden killer of write throughput. Consider using <span class="highlight">HOT (Heap-Only Tuples)</span> updates by ensuring that heavily updated columns are not indexed.</p>
      
      <h2>Conclusion</h2>
      <p>Scaling Postgres for heavy writes requires a deep understanding of its internal mechanics. By tuning your WAL, aggressively managing autovacuum, and being strategic about indexes, you can extract immense performance from a single node.</p>
    `
  };

  constructor(private route: ActivatedRoute) {}

  ngOnInit(): void {
    this.articleId = this.route.snapshot.paramMap.get('id');
    // In a real application, you would fetch the article data based on this.articleId
  }
}
